#cloud-config
hostname: ${hostname}
bootcmd:
  - echo "127.0.0.1 localhost" > /etc/hosts
locale: en_US.UTF-8
timezone: UTC
runcmd:
  - 'curl -o puppetlabs-release-pc1-el-7.noarch.rpm  https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm'
  - 'rpm -ivh puppetlabs-release-pc1-el-7.noarch.rpm'
  - 'yum install -y puppet-agent-${puppet_agent_version}'
  # We wait to be sure that puppet CA is ready
  - 'sleep 300'
  - '/opt/puppetlabs/bin/puppet agent -tv --server=${puppet_server_hostname}.${tld} --certname=${hostname}.${tld}'
  - '/opt/puppetlabs/bin/puppet agent -tv --server=${puppet_server_hostname}.${tld} --certname=${hostname}.${tld}'
final_message: "The system is up, after $UPTIME seconds"
