#cloud-config
hostname: ${hostname}
bootcmd:
  - echo "127.0.0.1 localhost" > /etc/hosts
locale: en_US.UTF-8
timezone: UTC
runcmd:
  - 'curl -o puppetlabs-release-pc1-el-7.noarch.rpm  https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm'
  - 'rpm -ivh puppetlabs-release-pc1-el-7.noarch.rpm'
  - 'yum install -y puppet-agent-${puppet_agent_version} puppetserver-${puppet_server_version} git'
  - 'cd /tmp && git clone https://github.com/renaudhager/puppet-bootstrap.git'
  - '/opt/puppetlabs/puppet/bin/puppet apply /tmp/puppet-bootstrap/puppetca.pp --debug'
  - 'systemctl start puppetserver'
  - '/opt/puppetlabs/bin/puppet agent -tv --server=${hostname}.${tld} --certname=${hostname}.${tld} --environment=${environment}'
final_message: "The system is up, after $UPTIME seconds"
